#!/usr/bin/env python3
"""
Convert ASCII STL files to binary STL format for MuJoCo compatibility.
"""

import struct
import os

def parse_ascii_stl(filename):
    """Parse ASCII STL file and return vertices and faces"""
    vertices = []
    faces = []

    with open(filename, 'r') as f:
        lines = f.readlines()

    i = 0
    while i < len(lines):
        line = lines[i].strip()
        if line.startswith('facet normal'):
            # Skip normal line
            i += 1
            continue
        elif line.startswith('vertex'):
            # Parse vertex
            parts = line.split()
            vertex = [float(parts[1]), float(parts[2]), float(parts[3])]
            vertices.append(vertex)
        elif line == 'endfacet':
            # End of face - collect last 3 vertices
            if len(vertices) >= 3:
                face = vertices[-3:]
                faces.append(face)
        i += 1

    return vertices, faces

def write_binary_stl(filename, faces):
    """Write faces to binary STL file"""
    with open(filename, 'wb') as f:
        # Header (80 bytes)
        header = b'Binary STL generated by Python script' + b'\x00' * (80 - len(b'Binary STL generated by Python script'))
        f.write(header)

        # Number of triangles (4 bytes)
        f.write(struct.pack('<I', len(faces)))

        # Write each triangle
        for face in faces:
            # Normal vector (12 bytes) - we'll use (0,0,1) for simplicity
            f.write(struct.pack('<fff', 0.0, 0.0, 1.0))

            # Three vertices (36 bytes)
            for vertex in face:
                f.write(struct.pack('<fff', vertex[0], vertex[1], vertex[2]))

            # Attribute byte count (2 bytes)
            f.write(struct.pack('<H', 0))

def convert_ascii_to_binary(ascii_filename, binary_filename):
    """Convert ASCII STL to binary STL"""
    try:
        vertices, faces = parse_ascii_stl(ascii_filename)
        write_binary_stl(binary_filename, faces)
        print(f"Converted: {ascii_filename} -> {binary_filename}")
        return True
    except Exception as e:
        print(f"Error converting {ascii_filename}: {e}")
        return False

def main():
    """Convert all shell STL files from ASCII to binary"""
    mesh_dir = 'meshes'
    shell_files = [
        'palm_stop_f1_lower_shell.stl',
        'palm_stop_f2_lower_shell.stl',
        'palm_stop_f1_upper_shell.stl',
        'palm_stop_f2_upper_shell.stl',
        'f1l1_stop_lower_shell.stl',
        'f1l1_stop_upper_shell.stl',
        'f2l1_stop_lower_shell.stl',
        'f2l1_stop_upper_shell.stl',
        'f1l1_l2stop_zero_shell.stl',
        'f1l1_l2stop_max_shell.stl',
        'f2l1_l2stop_zero_shell.stl',
        'f2l1_l2stop_max_shell.stl'
    ]

    print("Converting ASCII STL files to binary format...")

    converted = 0
    for filename in shell_files:
        ascii_path = os.path.join(mesh_dir, filename)
        binary_path = os.path.join(mesh_dir, filename)  # Overwrite with binary

        if os.path.exists(ascii_path):
            if convert_ascii_to_binary(ascii_path, binary_path):
                converted += 1
        else:
            print(f"File not found: {ascii_path}")

    print(f"Successfully converted {converted}/{len(shell_files)} STL files to binary format")

if __name__ == '__main__':
    main()
